name: 'Code signing action'
description: 'Sign a file with a code signing certificate.'
branding:
  icon: 'award'
  color: 'green'
inputs:
  certificate:
    description: 'The base64 encoded certificate.'
    required: true
  certificate-password:
    description: 'The password for opening the certificate'
    required: true
  certificate-sha1:
    description: 'The SHA-1 hash of the certificate'
    required: true
  folder:
    description: 'The folder that contains the files to sign.'
    required: true
  extensions:
    description: 'List of extentions for the files to sign.'
    required: false
  recursive:
    description: 'Recursively search for supported files.'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
