on: push

name: main
jobs:
  run_action:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Use node 12
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - run: npm install

      - run: npm run lint

      - name: Copy libraries
        shell: cmd
        run: |
          dir "C:/Program Files (x86)/Windows Kits/10/bin/"
          copy C:\Windows\System32\wmi.dll files
          cd files
          mkdir subdirectory
          copy C:\Windows\System32\wmi.dll subdirectory

      - name: Run the action with missing certificate
        uses: ./
        with:
          certificate: '${{ secrets.MISSING_CERTIFICATE }}'
          folder: 'files'

      - name: Run the action
        uses: ./
        with:
          certificate: '${{ secrets.CERTIFICATE }}'
          folder: 'files'
          recursive: true
